ccflags-y += -Idrivers/media/platform/msm/camera_v2_lenovo
ccflags-y += -Idrivers/media/platform/msm/camera_v2_lenovo/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_lenovo/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_lenovo/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
