ccflags-y += -Idrivers/media/platform/msm/camera-lenovo/camera-driver
ccflags-y += -Idrivers/media/platform/msm/camera-lenovo/camera-driver/isp/
ccflags-y += -Idrivers/media/platform/msm/camera-lenovo/camera-driver/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera-lenovo/camera-driver/common
obj-$(CONFIG_MSM_CPP) += msm_cpp_soc.o msm_cpp.o
