ccflags-y += -Idrivers/media/platform/msm/camera-lenovo/camera-driver/sensor/cci
ccflags-y += -Idrivers/media/platform/msm/camera-lenovo/camera-driver
ccflags-y += -Idrivers/media/platform/msm/camera-lenovo/camera-driver/common
ccflags-y += -Idrivers/media/platform/msm/camera-lenovo/camera-driver/sensor/io
obj-$(CONFIG_MSMB_CAMERA) += msm_flash.o
