ccflags-y += -Idrivers/media/platform/msm/camera_v2_lenovo
ccflags-y += -Idrivers/media/platform/msm/camera_v2_lenovo/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_lenovo/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_lenovo/common
obj-$(CONFIG_MSM_CPP) += msm_cpp_soc.o msm_cpp.o
