# Linux driver folder
obj-y += Config_FT5822.o
obj-y += Config_FT5X46.o
obj-y += Config_FT8606.o
obj-y += Config_FT6X36.o
obj-y += Config_FT3C47.o
obj-y += DetailThreshold.o
obj-y += Global.o ini.o
obj-y += Test_FT5822.o
obj-y += Test_FT5X46.o
obj-y += Test_FT8606.o
obj-y += Test_FT6X36.o
obj-y += Test_FT3C47.o
obj-y += test_lib.o

