ccflags-y += -Idrivers/media/platform/msm/camera_v2_lenovo
ccflags-y += -Idrivers/media/platform/msm/camera_v2_lenovo/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_lenovo/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_lenovo/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
